name: "Python Package Build and Check"
author: "namiyousef"
description: "Check for formatting, linting, static type checking and run tests"
runs:
  using: "composite"
  steps:
  - name: Build 
    shell: bash
    run: |
      python -m pip install .
      python -m pip install .[test]
  - name: Linting Checks
    shell: bash
    run: |
      flake8 .
  - name: Formatting Checks
    shell: bash
    run: |
      black --check .
  - name: Check isort check
    shell: bash
    run: |
      isort --check-only .
  - name: Unittest Checks
    shell: bash
    run: |
      coverage run -m pytest tests/
branding:
  icon: activity
  color: green